import {StrictMode,useEffect,useState,type ChangeEvent,type ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {HashRouter,Link,NavLink,Route,Routes,useLocation} from 'react-router-dom';
import {AlertTriangle,Award,BookOpen,ChevronRight,Download,Film,Home,Layers,Mic,Plus,Search,Sparkles,User,XCircle} from 'lucide-react';
import ShotFlowPage from './ShotFlowPage';
import QuoteCutPage from './QuoteCutPage';
import {B,Badge,Card,Input,ProjModal,TA,cn,dlFile,proxyOrDemo,toast,uid,usePM} from './shared';
import './index.css';

type Block={id:string;title:string;items:string[];verify?:boolean};
type MLProj={id:string;title:string;topic:string;bg:string;blocks:Block[]};
const defs:[string,string,boolean][]=[['value','选题价值',false],['audience','目标受众',false],['angles','报道角度',false],['sources','采访对象',false],['questions','采访问题',false],['facts','已知事实',true],['opinions','已知观点',true],['verify','待核实信息',true],['checklist','事实核查清单',true],['titles','平台标题方向',false]];
const demo:Record<string,string[]>={value:['聚焦AI对内容生产工作流的改变','兼具人物故事与行业议题价值'],audience:['应届毕业生','内容与AI产品从业者'],angles:['广电学生的AI转型','人机协作如何改变生产效率','AI内容的事实与伦理边界'],sources:['广电专业学生','新闻传播教师','短视频编导'],questions:['第一次使用AI创作的感受？','哪些工作可以提效？','哪些判断不能交给AI？'],facts:['AI可以快速生成脚本初稿','不同平台需要不同叙事结构'],opinions:['“AI只是工具，最终判断仍由人完成”','“AI降低了内容原型验证成本”'],verify:['核实受访者身份','核实效率数据及其统计口径'],checklist:['至少交叉验证两个来源','为数据标注出处','区分事实与观点'],titles:['短视频：用AI做内容的30天','公众号：AI时代内容人的价值','B站：从选题到粗剪的AI工作流']};
const newBlocks=()=>defs.map(([id,title,verify])=>({id,title,verify,items:[...(demo[id]||[])]}));
function MediaLens(){const{list,setList,aid,setAid,active}=usePM<MLProj>('ml-list','ml-active');const[topic,setTopic]=useState(''),[bg,setBg]=useState(''),[blocks,setBlocks]=useState<Block[]>(active?.blocks||[]),[loading,setLoading]=useState(''),[show,setShow]=useState(false),[ren,setRen]=useState(false),[name,setName]=useState('');
 useEffect(()=>{if(active){setTopic(active.topic);setBg(active.bg);setBlocks(active.blocks)}},[active?.id]);
 const persist=(bs=blocks,t=topic,b=bg)=>{setBlocks(bs);if(active)setList(list.map(p=>p.id===aid?{...p,topic:t,bg:b,blocks:bs}:p))};
 const create=()=>{const id=uid();setList([...list,{id,title:name.trim()||'媒眼项目',topic:'',bg:'',blocks:[]}]);setAid(id);setShow(false);setName('')};
 const remove=(id:string)=>{if(list.length<=1)return toast('至少保留一个项目');setList(list.filter(p=>p.id!==id));if(aid===id)setAid(list.find(p=>p.id!==id)?.id||'')};
 const rename=()=>{if(active&&name.trim())setList(list.map(p=>p.id===aid?{...p,title:name.trim()}:p));setRen(false);setName('')};
 const generate=async(id?:string)=>{setLoading(id||'all');const r=await proxyOrDemo(id?'medialens_regenerate':'medialens_generate',{topic,bg,section:id});if(id){const d=newBlocks().find(x=>x.id===id);if(d)persist(blocks.map(x=>x.id===id?{...d,items:d.items.map((v,i)=>i?v:v+'（重生成）')}:x))}else persist(newBlocks());if(!r.fromAI)toast('AI 服务暂不可用，已加载示例结果');setLoading('')};
 const exp=()=>{if(!active)return;dlFile(`${active.title}.md`,`# ${active.title}\n\n主题：${topic}\n\n${blocks.map(b=>`## ${b.title}${b.verify?'（待核实）':''}\n${b.items.map(x=>`- ${x}`).join('\n')}`).join('\n\n')}`)};
 if(!active)return <Empty icon={Search} title="媒眼 MediaLens" text="融媒体选题策划与事实框架助手" onClick={()=>setShow(true)} modal={<ProjModal open={show} onClose={()=>setShow(false)} list={list} aid={aid} setAid={setAid} onNew={create} onDel={remove} onRen={rename} Icon={Search} sub={(p:MLProj)=>`${p.blocks.length}类`} npn={name} setNpn={setName} renOpen={ren} setRenOpen={setRen}/>}/>;
 return <Page title="媒眼 MediaLens" sub="选题策划 · 事实框架助手" icon={Search} actions={<><B variant="outline" onClick={()=>setShow(true)}>项目：{active.title}</B><B variant="outline" onClick={exp}><Download className="size-3.5"/>导出</B></>}>
  <div className="grid grid-cols-1 lg:grid-cols-4 gap-4"><Card c="p-4 space-y-3"><label className="text-xs">主题</label><Input value={topic} onChange={(e:ChangeEvent<HTMLInputElement>)=>{setTopic(e.target.value);persist(blocks,e.target.value,bg)}}/><label className="text-xs">背景材料</label><TA value={bg} onChange={(v:string)=>{setBg(v);persist(blocks,topic,v)}} rows={4}/><B c="w-full" disabled={!!loading} onClick={()=>generate()}><Sparkles className="size-3.5"/>{loading==='all'?'生成中':'生成方案'}</B><B variant="outline" c="w-full" onClick={()=>{setTopic('AI时代广电学生的职业选择');setBg('传媒行业正经历生成式AI变革');persist(newBlocks())}}>加载示例</B><p className="text-[11px] text-amber-800"><AlertTriangle className="inline size-3"/> AI 内容需人工核实</p></Card>
  <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-2 gap-3">{!blocks.length&&<Card c="p-12 text-center text-sm text-muted-foreground md:col-span-2">点击生成策划方案</Card>}{blocks.map(b=><Card key={b.id} c="p-3"><div className="flex justify-between gap-2"><input value={b.title} onChange={e=>persist(blocks.map(x=>x.id===b.id?{...x,title:e.target.value}:x))} className="font-semibold text-sm bg-transparent min-w-0 flex-1"/>{b.verify&&<Badge v="amber">待核实</Badge>}<button aria-label="重新生成" onClick={()=>generate(b.id)}><Sparkles className="size-4 text-primary"/></button><button aria-label="添加条目" onClick={()=>persist(blocks.map(x=>x.id===b.id?{...x,items:[...x.items,'']}:x))}><Plus className="size-4"/></button></div>{b.items.map((item,i)=><div key={i} className="flex gap-1 mt-1"><input value={item} onChange={e=>persist(blocks.map(x=>x.id===b.id?{...x,items:x.items.map((v,j)=>i===j?e.target.value:v)}:x))} className="text-xs flex-1 min-w-0 bg-transparent"/><button aria-label="删除条目" onClick={()=>persist(blocks.map(x=>x.id===b.id?{...x,items:x.items.filter((_,j)=>j!==i)}:x))}><XCircle className="size-3.5"/></button></div>)}</Card>)}</div></div>
  <ProjModal open={show} onClose={()=>setShow(false)} list={list} aid={aid} setAid={setAid} onNew={create} onDel={remove} onRen={rename} Icon={Search} sub={(p:MLProj)=>`${p.blocks.length}类`} npn={name} setNpn={setName} renOpen={ren} setRenOpen={setRen}/>
 </Page>}
function Empty({icon:Icon,title,text,onClick,modal}:{icon:any;title:string;text:string;onClick:()=>void;modal:ReactNode}){return <div className="max-w-md mx-auto px-4 py-20 text-center"><Icon className="size-12 mx-auto text-primary/40"/><h2 className="text-xl font-serif font-bold mt-3">{title}</h2><p className="text-sm text-muted-foreground my-3">{text}</p><B onClick={onClick}><Plus className="size-4"/>新建或打开项目</B>{modal}</div>}
function Page({title,sub,icon:Icon,actions,children}:{title:string;sub:string;icon:any;actions?:ReactNode;children:ReactNode}){return <div className="max-w-7xl mx-auto px-4 py-6"><div className="flex justify-between gap-2 flex-wrap mb-4"><div className="flex gap-2"><Icon className="size-8 p-1.5 rounded bg-primary/10 text-primary"/><div><h1 className="text-lg font-serif font-bold">{title}</h1><p className="text-[11px] text-muted-foreground">{sub}</p></div></div><div className="flex gap-1.5 flex-wrap">{actions}</div></div>{children}</div>}
const nav=[['/','首页',Home],['/medialens','媒眼',Search],['/shotflow','镜序',Film],['/quotecut','声迹',Mic],['/documentary','微纪录片',BookOpen],['/narrative-exp','叙事实验',Layers]] as const;
function Layout({children}:{children:ReactNode}){const loc=useLocation();return <div className="min-h-screen flex flex-col bg-background"><header className="sticky top-0 z-40 bg-background/90 border-b"><div className="max-w-7xl mx-auto px-4 h-14 flex justify-between items-center"><Link to="/" className="font-serif font-bold">AI × 融媒体作品集</Link><nav className="hidden md:flex">{nav.map(([p,l,I])=><NavLink key={p} to={p} className={cn('px-2.5 py-1.5 rounded text-xs flex gap-1',loc.pathname===p?'bg-primary/10 text-primary':'text-muted-foreground')}><I className="size-3.5"/>{l}</NavLink>)}</nav></div></header><main className="flex-1">{children}</main><footer className="border-t py-4 text-center text-[10px] text-muted-foreground">广播电视学 · AI 产品经理候选人｜姓名、邮箱、简历待补充</footer></div>}
const projects=[['/medialens','媒眼 MediaLens','选题策划与事实框架',Search],['/shotflow','镜序 ShotFlow','短视频脚本与分镜',Film],['/quotecut','声迹 QuoteCut','采访检索与粗剪',Mic],['/documentary','《河流边的青春切片》','互动微纪录片 · 待采访',BookOpen],['/narrative-exp','一份素材，三种叙事','跨平台叙事实验 · 待补充',Layers]] as const;
function HomePage(){return <><section className="py-16 text-center bg-gradient-to-br from-teal-500/5 to-purple-500/5"><Badge v="outline">广播电视学 × AI 产品经理</Badge><h1 className="text-2xl md:text-4xl font-serif font-bold my-3">用 AI 重新定义内容生产工作流</h1><p className="text-sm text-muted-foreground">发现问题 → 定义方案 → Coding实现 → 内容验证 → 反馈迭代</p></section><section className="max-w-6xl mx-auto p-4 py-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{projects.map(([p,t,s,I])=><Link key={p} to={p}><Card c="p-5 h-full hover:border-primary/40"><I className="size-9 p-2 rounded bg-primary/10 text-primary"/><h2 className="font-semibold mt-3">{t}</h2><p className="text-xs text-muted-foreground mt-1">{s}</p></Card></Link>)}<Card c="p-4 md:col-span-2 lg:col-span-3 bg-amber-50 border-amber-200 text-xs text-amber-800"><AlertTriangle className="inline size-4 mr-1"/>所有未完成真实数据、个人履历和采访材料均标记“待补充”，不编造。</Card></section></>}
function Documentary(){return <Page title="《河流边的青春切片》" sub="互动微纪录片 · 待采访" icon={BookOpen}><Card c="p-4 bg-amber-50 border-amber-200 text-xs text-amber-800">所有人物、故事和数据均为待采访占位。内容原则：一个核心人物、一个具体场景、一个明确问题、一条可验证叙事线。</Card></Page>}
function Narrative(){const[t,setT]=useState(0),tabs=['电视新闻版','竖屏短视频','播客版'];return <Page title="一份素材，三种叙事" sub="跨平台叙事对比实验 · 待补充" icon={Layers}><div className="flex gap-1 mb-3">{tabs.map((x,i)=><button key={x} onClick={()=>setT(i)} className={cn('flex-1 p-2 rounded border text-xs',t===i&&'bg-primary text-primary-foreground')}>{x}</button>)}</div><Card c="p-4 text-sm">标题、开场、内容顺序、片段取舍、字幕密度、语言风格、目标受众、人工修改和AI建议采纳情况：<Badge v="amber">待真实素材补充</Badge></Card></Page>}
function NotFound(){return <div className="py-24 text-center"><h1 className="text-5xl font-bold">404</h1><Link to="/"><B c="mt-4">返回首页</B></Link></div>}
function App(){return <HashRouter><Layout><Routes><Route path="/" element={<HomePage/>}/><Route path="/medialens" element={<MediaLens/>}/><Route path="/shotflow" element={<ShotFlowPage/>}/><Route path="/quotecut" element={<QuoteCutPage/>}/><Route path="/documentary" element={<Documentary/>}/><Route path="/narrative-exp" element={<Narrative/>}/><Route path="*" element={<NotFound/>}/></Routes></Layout></HashRouter>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
