import {useEffect,useMemo,useRef,useState,type ChangeEvent,type MouseEvent} from 'react';
import {Check,Download,Mic,Pause,Play,Plus,Search,ShieldCheck,Sparkles,Trash2,X,Zap} from 'lucide-react';
import {B,Badge,Card,Input,ProjModal,TA,cn,dlFile,fmtTime,parseT,proxyOrDemo,toast,uid,usePM} from './shared';
type TLine={idx:number;start:number;end:number;text:string};type Quote={idx:number;reason:string;cat:string};type QCProj={id:string;title:string;mode:string;raw:string;lines:TLine[];quotes:Quote[];selected:number[];titleQ:string};
const SAMPLE=`1\n00:00:02,100 --> 00:00:05,300\n我是广电专业大四学生。\n\n2\n00:00:06,000 --> 00:00:09,500\n传统媒体在变化，压力也带来机会。\n\n3\n00:00:10,200 --> 00:00:14,800\n第一次用AI写脚本，确实很震撼。\n\n4\n00:00:15,000 --> 00:00:19,200\n但用多了发现，它少了人的感觉。\n\n5\n00:00:20,000 --> 00:00:24,500\n真正打动人的故事，还是要靠人判断。\n\n6\n00:00:25,000 --> 00:00:29,000\nAI节省机械劳动，核心创意不能替代。`;
const DEMO:Quote[]=[{idx:1,cat:'事实',reason:'点明行业背景'},{idx:2,cat:'经历',reason:'个人经历有画面感'},{idx:3,cat:'观点',reason:'对AI局限的判断'},{idx:4,cat:'情绪表达',reason:'适合结尾升华'},{idx:5,cat:'观点',reason:'总结人机协作价值'}];
const parseSRT=(s:string)=>{const r:TLine[]=[];for(const b of s.replace(/\r/g,'').trim().split(/\n\s*\n/)){const l=b.split('\n'),m=l.find(x=>x.includes('-->'))?.match(/(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})/);if(m){const ti=l.findIndex(x=>x.includes('-->'));r.push({idx:r.length+1,start:parseT(m[1]),end:parseT(m[2]),text:l.slice(ti+1).join(' ').trim()})}}return r};
const exportMd=(p:QCProj)=>`# ${p.title}\n\n${p.quotes.map(q=>{const l=p.lines[q.idx];return l?`## ${q.cat} ${fmtTime(l.start)}\n> ${l.text}\n\n${q.reason}`:''}).join('\n\n')}\n\n## 粗剪\n${p.selected.map(i=>p.lines[i]).filter(Boolean).map(l=>`- ${fmtTime(l.start)} ${l.text}`).join('\n')}`;
export default function QuoteCutPage(){const{list,setList,aid,setAid,active}=usePM<QCProj>('qc-list','qc-active');const[raw,setRaw]=useState(''),[mode,setMode]=useState<'srt'|'text'>('srt'),[lines,setLines]=useState<TLine[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[selected,setSelected]=useState<number[]>([]),[title,setTitle]=useState(''),[query,setQuery]=useState(''),[cat,setCat]=useState('all'),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[tab,setTab]=useState('lines'),[loading,setLoading]=useState(false),[draft,setDraft]=useState(false),[show,setShow]=useState(false),[ren,setRen]=useState(false),[name,setName]=useState('');const timer=useRef<number|null>(null);
 useEffect(()=>{if(active){setRaw(active.raw);setMode(active.mode as any);setLines(active.lines);setQuotes(active.quotes);setSelected(active.selected);setTitle(active.titleQ)}},[active?.id]);const save=(patch:Partial<QCProj>)=>{if(active)setList(list.map(p=>p.id===aid?{...p,mode,raw,lines,quotes,selected,titleQ:title,...patch}:p))};const duration=lines.at(-1)?.end||60;
 useEffect(()=>{if(playing)timer.current=window.setInterval(()=>setTime(t=>t+.1>=duration?(setPlaying(false),duration):t+.1),100);return()=>{if(timer.current)clearInterval(timer.current)}},[playing,duration]);
 const parse=()=>{const ls=mode==='srt'?parseSRT(raw):raw.split('\n').filter(Boolean).map((text,i)=>({idx:i+1,start:i*8,end:(i+1)*8,text}));if(!ls.length){toast(mode==='srt'?'SRT格式错误，请检查时间码':'请输入逐字稿');return}setLines(ls);setQuotes([]);setSelected([]);save({lines:ls,quotes:[],selected:[]})};
 const analyze=async()=>{if(!lines.length)return toast('请先解析文本');setLoading(true);const r=await proxyOrDemo('quotecut_analyze',{raw,mode});const qs=DEMO.filter(q=>lines[q.idx]);setQuotes(qs);save({quotes:qs});if(!r.fromAI)toast('AI 服务暂不可用，已加载示例结果');setLoading(false)};
 const rough=async(target:number)=>{const r=await proxyOrDemo('quotecut_rough',{lines,quotes,target});const pool=(quotes.length?quotes.map(q=>q.idx):lines.map((_,i)=>i)).sort((a,b)=>lines[a].start-lines[b].start);let total=0;const pick:number[]=[];for(const i of pool){const d=lines[i].end-lines[i].start;if(total+d<=target){pick.push(i);total+=d}}setSelected(pick);setDraft(!r.fromAI);save({selected:pick});if(!r.fromAI)toast('AI 组合失败，已按时间顺序生成可编辑草稿')};
 const create=()=>{const id=uid();setList([...list,{id,title:name.trim()||'声迹项目',mode:'srt',raw:'',lines:[],quotes:[],selected:[],titleQ:''}]);setAid(id);setShow(false);setName('')};const remove=(id:string)=>{if(list.length<=1)return toast('至少保留一个项目');setList(list.filter(p=>p.id!==id));if(aid===id)setAid(list.find(p=>p.id!==id)?.id||'')};const rename=()=>{if(active&&name.trim())setList(list.map(p=>p.id===aid?{...p,title:name.trim()}:p));setRen(false);setName('')};
 const load=()=>{const ls=parseSRT(SAMPLE);setRaw(SAMPLE);setMode('srt');setLines(ls);setQuotes(DEMO);setSelected([]);save({raw:SAMPLE,mode:'srt',lines:ls,quotes:DEMO,selected:[]})};const filtered=quotes.filter(q=>(cat==='all'||q.cat===cat)&&lines[q.idx]?.text.includes(query));const total=selected.reduce((s,i)=>s+(lines[i]?.end-lines[i]?.start||0),0);
 return <div className="max-w-7xl mx-auto px-4 py-6"><div className="flex justify-between flex-wrap gap-2 mb-4"><div><h1 className="text-lg font-serif font-bold">声迹 QuoteCut <Badge v="amber">主项目</Badge></h1><p className="text-[11px] text-muted-foreground">采访检索 · 金句提取 · 粗剪</p></div><div className="flex gap-1"><B variant="outline" onClick={()=>setShow(true)}>项目：{active?.title||'未创建'}</B><B variant="outline" onClick={()=>active&&dlFile(`${active.title}.md`,exportMd(active))}><Download className="size-3.5"/>导出</B><B variant="outline" onClick={()=>{setRaw('');setLines([]);setQuotes([]);setSelected([]);save({raw:'',lines:[],quotes:[],selected:[]})}}><Trash2 className="size-3.5"/>清空</B></div></div>
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="space-y-3"><Card c="p-3 text-center"><b className="font-mono">{fmtTime(time)}</b> / {fmtTime(duration)}<div className="mt-2"><B size="icon" aria-label={playing?'暂停':'播放'} onClick={()=>setPlaying(!playing)}>{playing?<Pause className="size-4"/>:<Play className="size-4"/>}</B></div><div className="h-2 bg-muted mt-2 rounded cursor-pointer" onClick={(e:MouseEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();setTime((e.clientX-r.left)/r.width*duration)}}><div className="h-full bg-primary rounded" style={{width:`${time/duration*100}%`}}/></div><p className="text-[10px] text-muted-foreground mt-2"><ShieldCheck className="inline size-3"/> 演示播放器，不上传音频</p></Card><Card c="p-3"><div className="flex gap-1 mb-2"><B variant={mode==='srt'?'default':'outline'} onClick={()=>setMode('srt')}>SRT</B><B variant={mode==='text'?'default':'outline'} onClick={()=>setMode('text')}>普通文本</B></div><TA value={raw} onChange={setRaw} rows={7}/><div className="flex gap-1 mt-2"><B variant="outline" onClick={parse}>解析</B><B variant="outline" onClick={load}>加载示例</B></div><label className="text-xs block mt-2">项目标题</label><Input value={title} onChange={(e:ChangeEvent<HTMLInputElement>)=>{setTitle(e.target.value);save({titleQ:e.target.value})}}/></Card><Card c="p-3"><h3 className="text-xs font-semibold"><Zap className="inline size-3.5"/> AI金句提取</h3><B c="w-full mt-2" disabled={loading||!lines.length} onClick={analyze}><Sparkles className="size-3.5"/>{loading?'分析中':'提取金句'}</B></Card></div>
 <Card c="p-3 lg:col-span-2"><div className="flex border-b mb-3">{[['lines','逐字稿'],['quotes',`金句(${quotes.length})`],['rough',`粗剪(${selected.length})`]].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={cn('px-3 py-2 text-xs',tab===k&&'border-b-2 border-primary text-primary')}>{l}</button>)}</div>
 {tab==='lines'&&<div className="max-h-[65vh] overflow-y-auto">{!lines.length?<p className="text-center text-sm text-muted-foreground py-8">请先解析文本</p>:lines.map((l,i)=><div key={l.idx} onClick={()=>setTime(l.start)} className={cn('flex gap-2 p-2 rounded cursor-pointer',selected.includes(i)&&'bg-amber-50')}><span className="font-mono text-[10px] w-16">{fmtTime(l.start)}</span><span className="text-xs flex-1">{l.text}</span><button aria-label={selected.includes(i)?'移出粗剪':'加入粗剪'} onClick={e=>{e.stopPropagation();const n=selected.includes(i)?selected.filter(x=>x!==i):[...selected,i];setSelected(n);save({selected:n})}}>{selected.includes(i)?<Check className="size-4"/>:<Plus className="size-4"/>}</button></div>)}</div>}
 {tab==='quotes'&&<><div className="flex gap-2 mb-2"><div className="relative flex-1"><Search className="absolute left-2 top-2.5 size-3.5"/><Input c="pl-7" value={query} onChange={(e:ChangeEvent<HTMLInputElement>)=>setQuery(e.target.value)}/></div><select value={cat} onChange={e=>setCat(e.target.value)} className="border rounded px-2 text-xs"><option value="all">全部</option>{['事实','观点','经历','情绪表达'].map(x=><option key={x}>{x}</option>)}</select></div>{filtered.map((q,i)=>{const l=lines[q.idx];return <Card key={i} c="p-3 mb-2"><Badge v="outline">{q.cat}</Badge><button className="ml-2 text-xs font-mono" onClick={()=>setTime(l.start)}>{fmtTime(l.start)}</button><p className="text-sm mt-2">“{l.text}”</p><p className="text-xs text-muted-foreground">{q.reason}</p></Card>})}</>}
 {tab==='rough'&&<><div className="flex gap-1 flex-wrap mb-3"><Badge v="outline">{selected.length}段 · {fmtTime(total)}</Badge>{draft&&<Badge v="amber">Demo草稿</Badge>}<B variant="outline" onClick={()=>rough(60)}>1分钟</B><B variant="outline" onClick={()=>rough(180)}>3分钟</B></div>{selected.map((i,n)=><div key={i} className="p-2 bg-amber-50 border rounded mb-1 text-xs"><b>{n+1}. {fmtTime(lines[i].start)}</b> {lines[i].text}<button aria-label="移出粗剪" className="float-right" onClick={()=>setSelected(selected.filter(x=>x!==i))}><X className="size-4"/></button></div>)}</>}
 </Card></div><ProjModal open={show} onClose={()=>setShow(false)} list={list} aid={aid} setAid={setAid} onNew={create} onDel={remove} onRen={rename} Icon={Mic} sub={(p:QCProj)=>`${p.lines.length}条`} npn={name} setNpn={setName} renOpen={ren} setRenOpen={setRen}/></div>;
}
