import { useState,useEffect,useMemo,type ChangeEvent,type MouseEvent } from 'react';
import { Plus,Trash2,Edit3,X } from 'lucide-react';
const LS=localStorage;
export const lsGet=<T,>(k:string,d:T):T=>{try{const v=LS.getItem(k);return v?JSON.parse(v):d}catch{return d}};
export const lsSet=(k:string,v:unknown)=>{try{LS.setItem(k,JSON.stringify(v))}catch{}};
export const cn=(...a:unknown[])=>a.filter(Boolean).join(' ');
export const uid=()=>Math.random().toString(36).slice(2,10);
export const fmtTime=(s:number)=>{const m=Math.floor(s/60),r=Math.floor(s%60),ms=Math.floor((s%1)*100);return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}.${String(ms).padStart(2,'0')}`};
export const parseT=(t:string)=>{const p=t.trim().split(':');if(p.length<2)return 0;const[h,m,s]=p.length===3?p:['0',p[0],p[1]];return Number(h)*3600+Number(m)*60+parseFloat(s.replace(',','.'))};
export const dlFile=(n:string,c:string,type='text/markdown')=>{const b=new Blob([c],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)};
let toastTimer:number|null=null;
export function toast(msg:string){let el=document.getElementById('__toast');if(!el){el=document.createElement('div');el.id='__toast';el.className='fixed top-4 left-1/2 -translate-x-1/2 z-[100] px-3 py-2 rounded-md bg-foreground text-background text-xs shadow-md transition-opacity duration-200 pointer-events-none';document.body.appendChild(el)}el.textContent=msg;el.style.opacity='1';if(toastTimer)clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>{if(el)el.style.opacity='0'},2200)}
const AI_PROXY_URL=(import.meta as any).env?.VITE_AI_PROXY_URL as string|undefined;
export async function proxyOrDemo(task:string,payload:unknown):Promise<{ok:boolean;data?:unknown;fromAI:boolean}>{if(!AI_PROXY_URL)return{ok:true,fromAI:false};try{const res=await fetch(AI_PROXY_URL.replace(/\/$/,''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,payload})});if(!res.ok)throw new Error(`HTTP ${res.status}`);return{ok:true,data:await res.json(),fromAI:true}}catch{return{ok:true,fromAI:false}}}
export function usePM<T extends{id:string;title?:string}>(k:string,ak:string){const[list,setList]=useState<T[]>(()=>lsGet<T[]>(k,[]));const[aid,setAid]=useState<string>(()=>lsGet<string>(ak,''));useEffect(()=>lsSet(k,list),[list,k]);useEffect(()=>lsSet(ak,aid),[aid,ak]);const active=useMemo(()=>list.find(p=>p.id===aid)||null,[list,aid]);return{list,setList,aid,setAid,active}}
export const B=({c,children,variant='default',size='sm',...p}:any)=>{const va:any={default:'bg-primary text-primary-foreground hover:bg-primary/90',outline:'border border-border/60 bg-background hover:bg-accent/50',ghost:'hover:bg-accent/50 text-muted-foreground'},sz:any={sm:'h-8 px-3 text-xs',icon:'h-8 w-8'};return <button className={cn('inline-flex items-center justify-center gap-1.5 rounded-md font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-ring/30 disabled:opacity-50 disabled:pointer-events-none',va[variant],sz[size],c)} {...p}>{children}</button>};
export const Badge=({c,children,v='default'}:any)=>{const vs:any={default:'bg-primary/10 text-primary',outline:'border border-border/60 text-foreground/70',amber:'bg-amber-100 text-amber-800 border border-amber-200',green:'bg-green-100 text-green-800 border border-green-200',red:'bg-red-100 text-red-700 border border-red-200'};return <span className={cn('inline-flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium rounded-md',vs[v],c)}>{children}</span>};
export const Card=({c,children}:any)=><div className={cn('rounded-lg border border-border/40 bg-card shadow-sm',c)}>{children}</div>;
export const Input=({c,...p}:any)=><input className={cn('w-full h-9 px-3 text-sm rounded-md border border-input bg-background focus:outline-none focus:ring-2 focus:ring-ring/30',c)} {...p}/>;
export const TA=({value,onChange,c,...p}:any)=><textarea value={value} onChange={(e:ChangeEvent<HTMLTextAreaElement>)=>onChange?.(e.target.value)} className={cn('w-full px-3 py-2 text-sm rounded-md border border-input bg-background resize-y focus:outline-none focus:ring-2 focus:ring-ring/30',c)} {...p}/>;
export const Modal=({t,children,onClose,w}:any)=><div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50" onClick={onClose}><div className={cn('w-full bg-card rounded-lg shadow-xl max-h-[85vh] flex flex-col',w||'max-w-md')} onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between px-4 py-3 border-b border-border/40"><h3 className="text-sm font-semibold">{t}</h3><button onClick={onClose} className="p-1 rounded hover:bg-accent" aria-label="关闭"><X className="size-4"/></button></div><div className="p-4 overflow-y-auto flex-1">{children}</div></div></div>;
export function ProjModal({open,onClose,list,aid,setAid,onNew,onDel,onRen,Icon,sub,npn,setNpn,renOpen,setRenOpen}:any){if(!open)return null;return <Modal t="项目管理" onClose={onClose}><div className="flex gap-2 mb-3"><Input value={npn} onChange={(e:ChangeEvent<HTMLInputElement>)=>setNpn(e.target.value)} placeholder="新项目名称"/><B onClick={onNew}><Plus className="size-3.5"/>新建</B></div>{!list.length&&<p className="text-xs text-muted-foreground text-center py-3">暂无项目</p>}{list.map((p:any)=><div key={p.id} className={cn('p-2 rounded flex items-center gap-2 cursor-pointer',p.id===aid?'bg-primary/10':'hover:bg-accent/50')} onClick={()=>{setAid(p.id);onClose()}}><Icon className="size-4 text-muted-foreground shrink-0"/><span className="flex-1 truncate text-sm">{p.title||'未命名'}</span><span className="text-[10px] text-muted-foreground">{typeof sub==='function'?sub(p):sub}</span><button onClick={(e:MouseEvent)=>{e.stopPropagation();setNpn(p.title||'');setAid(p.id);setRenOpen(true)}} className="p-1 hover:bg-accent rounded" aria-label="重命名"><Edit3 className="size-3.5"/></button><button onClick={(e:MouseEvent)=>{e.stopPropagation();onDel(p.id)}} className="p-1 hover:bg-red-100 rounded text-red-500" aria-label="删除项目"><Trash2 className="size-3.5"/></button></div>)}{renOpen&&<Modal t="重命名" onClose={()=>setRenOpen(false)}><Input value={npn} onChange={(e:ChangeEvent<HTMLInputElement>)=>setNpn(e.target.value)}/><div className="flex justify-end gap-2 mt-3"><B variant="outline" onClick={()=>setRenOpen(false)}>取消</B><B onClick={onRen}>确定</B></div></Modal>}</Modal>}
