import { useState, useMemo, useEffect, type DragEvent, type ChangeEvent } from 'react';
import { Film, Sparkles, Plus, Trash2, Edit3, Download, GripVertical, Lock, Unlock, Clock, Save, Eye, History } from 'lucide-react';
import { usePM, uid, cn, B, Badge, Card, Input, TA, Modal, ProjModal, dlFile, proxyOrDemo, toast } from './shared';

export type Shot={id:string;n:number;dur:number;st:string;cam:string;desc:string;act:string;vo:string;sub:string;audio:string;tr:string;prompt:string;locked?:boolean};
export type SFProj={id:string;title:string;brief:any;shots:Shot[];versions:{id:string;name:string;ts:number;shots:Shot[]}[]};
const SF_DEMO:Shot[]=[
{id:'s1',n:1,dur:5,st:'全景',cam:'固定',desc:'清晨薄雾笼罩古镇河面',act:'人物骑车沿河边前行',vo:'这是一座依河而建的古镇。',sub:'清晨 6:00',audio:'河水声+鸟鸣',tr:'切',prompt:'ancient town river morning mist'},
{id:'s2',n:2,dur:8,st:'中景',cam:'跟拍',desc:'人物走进工作室放下背包',act:'推门开电脑',vo:'一位广电学生正在用AI完成内容项目。',sub:'人物采访',audio:'门铃声+键盘声',tr:'切',prompt:'young creator entering studio'},
{id:'s3',n:3,dur:10,st:'近景',cam:'固定',desc:'电脑屏幕显示AI对话界面',act:'输入文字',vo:'以前写脚本要两三天，AI几小时出初版。',sub:'AI辅助生成',audio:'键盘声+轻音乐',tr:'叠化',prompt:'laptop AI chat typing hands'}];
const expCSV=(shots:Shot[],name:string)=>{const h='镜头号,时长,景别,机位,画面,动作,旁白,字幕,音效,转场,提示词';const r=shots.map(s=>[s.n,s.dur,s.st,s.cam,s.desc,s.act,s.vo,s.sub,s.audio,s.tr,s.prompt].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','));dlFile(`${name}.csv`,'\ufeff'+h+'\n'+r.join('\n'),'text/csv')};
const expShoot=(shots:Shot[],name:string)=>dlFile(`${name}-拍摄清单.md`,`# ${name} - 拍摄清单\n\n${shots.map(s=>`## ${s.n}. ${s.desc}（${s.dur}s）\n- ${s.st} / ${s.cam}\n- 动作：${s.act}\n- [ ] 已拍\n`).join('\n')}`);
function mergeLocked(locked:Shot[],base:Shot[],total:number):Shot[]{if(total<=0)return base.map((s,i)=>({...s,id:uid(),n:i+1}));const count=Math.max(total,...locked.map(s=>s.n),locked.length);const result:Shot[]=[];const lockedByN=new Map(locked.map(s=>[s.n,s]));let baseIdx=0;for(let i=1;i<=count;i++){const ls=lockedByN.get(i);if(ls)result.push({...ls,n:i});else{const bs=base[baseIdx%base.length];result.push({...bs,id:uid(),n:i});baseIdx++}}return result}
function ShotCard({s,onEdit,onLock,onDel,onRegen,onDS,onDO,onDr,loading}:any){return <div draggable onDragStart={(e:DragEvent)=>onDS(e,s.id)} onDragOver={(e:DragEvent)=>onDO(e)} onDrop={(e:DragEvent)=>onDr(e,s.id)} className={cn('p-2.5 rounded-lg border transition-all',s.locked?'border-green-300 bg-green-50/50':'border-border/40 bg-card hover:border-primary/30',loading===s.id&&'opacity-60')}><div className="flex items-start gap-2"><div className="cursor-move text-muted-foreground/50 pt-1"><GripVertical className="size-4"/></div><div className="w-7 h-7 shrink-0 rounded bg-primary/10 text-primary flex items-center justify-center text-xs font-bold">{s.n}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-1.5 mb-1 flex-wrap"><Badge v="outline">{s.st}</Badge><Badge v="outline">{s.cam}</Badge><Badge v="outline">{s.dur}s</Badge>{s.locked&&<Badge v="green"><Lock className="size-2.5"/>锁定</Badge>}</div><div className="text-xs font-medium truncate">{s.desc}</div>{s.vo&&<div className="text-[11px] text-muted-foreground mt-0.5 line-clamp-1">🎙 {s.vo}</div>}</div><div className="flex items-center gap-0.5 shrink-0"><button onClick={()=>onRegen(s.id)} className="p-1 rounded hover:bg-accent text-primary" aria-label="重新生成本镜头"><Sparkles className="size-3.5"/></button><button onClick={()=>onLock(s.id)} className="p-1 rounded hover:bg-accent" aria-label={s.locked?'解锁镜头':'锁定镜头'}>{s.locked?<Unlock className="size-3.5 text-green-600"/>:<Lock className="size-3.5 text-muted-foreground"/>}</button><button onClick={()=>onEdit(s.id)} className="p-1 rounded hover:bg-accent text-muted-foreground" aria-label="编辑镜头"><Edit3 className="size-3.5"/></button><button onClick={()=>onDel(s.id)} className="p-1 rounded hover:bg-red-100 text-muted-foreground hover:text-red-500" disabled={s.locked} aria-label="删除镜头"><Trash2 className="size-3.5"/></button></div></div>{loading===s.id&&<div className="mt-2 text-[10px] text-primary">生成中...</div>}</div>}
export default function ShotFlowPage(){
 const{list,setList,aid,setAid,active}=usePM<SFProj>('gh-sf-list','gh-sf-active');
 const[brief,setBrief]=useState<any>({topic:'',platform:'抖音',duration:60,audience:'',type:'vlog',text:''});const[shots,setShots]=useState<Shot[]>(()=>active?.shots||[]);const[loading,setLoading]=useState<string|null>(null);const[editId,setEditId]=useState<string|null>(null);const[showP,setShowP]=useState(false),[showV,setShowV]=useState(false),[showC,setShowC]=useState(false);const[cmpV1,setCmpV1]=useState('curr'),[cmpV2,setCmpV2]=useState('');const[dragId,setDragId]=useState<string|null>(null);const[npn,setNpn]=useState(''),[renO,setRenO]=useState(false),[vn,setVn]=useState('');
 useEffect(()=>{if(active){setBrief(active.brief);setShots(active.shots)}},[active?.id]);
 const save=(sh:Shot[])=>{setShots(sh);if(active)setList(list.map(p=>p.id===aid?{...p,brief,shots:sh}:p))};const updB=(k:string,v:unknown)=>{const nb={...brief,[k]:v};setBrief(nb);if(active)setList(list.map(p=>p.id===aid?{...p,brief:nb}:p))};const total=useMemo(()=>shots.reduce((s,x)=>s+x.dur,0),[shots]),max=brief.duration||60,over=total>max;
 const newP=()=>{const id=uid();setList([...list,{id,title:npn.trim()||'未命名项目',brief:{topic:'',platform:'抖音',duration:60,audience:'',type:'vlog',text:''},shots:[],versions:[]}]);setAid(id);setShowP(false);setNpn('')};const delP=(id:string)=>{if(list.length<=1){toast('至少保留一个项目');return}setList(list.filter(p=>p.id!==id));if(aid===id)setAid('')};const renP=()=>{if(!active||!npn.trim())return;setList(list.map(p=>p.id===aid?{...p,title:npn.trim()}:p));setRenO(false);setNpn('')};
 const genAll=async()=>{const d=Number(brief.duration);if(!Number.isInteger(d)||d<15){toast('目标时长必须为不小于 15 秒的正整数');return}setLoading('all');try{const res=await proxyOrDemo('shotflow_generate',{...brief,duration:d});save(mergeLocked(shots.filter(s=>s.locked),SF_DEMO,shots.length||SF_DEMO.length));if(!res.fromAI)toast('AI 服务暂不可用，已加载示例结果')}finally{setLoading(null)}};
 const genOne=async(id:string)=>{setLoading(id);try{const res=await proxyOrDemo('shotflow_regenerate',{shotId:id,brief});const idx=shots.findIndex(s=>s.id===id);if(idx<0)return;const demo=SF_DEMO[idx%SF_DEMO.length],ns=[...shots];ns[idx]={...ns[idx],desc:demo.desc+'（重生成）',vo:demo.vo,act:demo.act,prompt:demo.prompt};save(ns);if(!res.fromAI)toast('AI 服务暂不可用，已加载示例结果')}finally{setLoading(null)}};
 const delShot=(id:string)=>save(shots.filter(s=>s.id!==id).map((s,i)=>({...s,n:i+1})));const addShot=()=>save([...shots,{id:uid(),n:shots.length+1,dur:5,st:'中景',cam:'固定',desc:'',act:'',vo:'',sub:'',audio:'',tr:'切',prompt:''}]);const toggleLock=(id:string)=>save(shots.map(s=>s.id===id?{...s,locked:!s.locked}:s));
 const onDS=(_e:DragEvent,id:string)=>setDragId(id),onDO=(e:DragEvent)=>e.preventDefault(),onDr=(_e:DragEvent,tgt:string)=>{if(!dragId||dragId===tgt)return;const si=shots.findIndex(s=>s.id===dragId),ti=shots.findIndex(s=>s.id===tgt),ns=[...shots],[m]=ns.splice(si,1);ns.splice(ti,0,m);save(ns.map((s,i)=>({...s,n:i+1})));setDragId(null)};
 const updShot=(id:string,k:string,v:unknown)=>{if(k==='dur'){const n=Number(v);if(!Number.isInteger(n)||n<=0)return;save(shots.map(s=>s.id===id?{...s,dur:n}:s))}else save(shots.map(s=>s.id===id?{...s,[k]:v}:s))};
 const saveVer=()=>{if(!active||!vn.trim())return;const v={id:uid(),name:vn.trim(),ts:Date.now(),shots:JSON.parse(JSON.stringify(shots))};setList(list.map(p=>p.id===aid?{...p,versions:[...p.versions,v]}:p));setVn('');setShowV(false)};
 const cmpRes=useMemo(()=>{if(!active)return{a:0,d:0,m:0,u:0};const s1:Shot[]=cmpV1==='curr'?shots:(active.versions.find(v=>v.id===cmpV1)?.shots||[]),s2:Shot[]=cmpV2==='curr'?shots:(active.versions.find(v=>v.id===cmpV2)?.shots||[]);if(!s1.length||!s2.length)return{a:0,d:0,m:0,u:0};let a=0,d=0,m=0,u=0;const m1=new Map(s1.map(s=>[s.n,s])),m2=new Map(s2.map(s=>[s.n,s]));m2.forEach((s,n)=>{if(!m1.has(n))a++;else{const o=m1.get(n)!;(o.desc!==s.desc||o.dur!==s.dur||o.vo!==s.vo)?m++:u++}});m1.forEach((_,n)=>{if(!m2.has(n))d++});return{a,d,m,u}},[cmpV1,cmpV2,shots,active]);
 if(!active)return <div className="max-w-3xl mx-auto px-4 py-20 text-center"><Film className="size-12 mx-auto mb-3 text-purple-300"/><h2 className="text-lg font-serif font-bold">镜序 ShotFlow</h2><p className="text-sm text-muted-foreground mb-4">AI 短视频脚本与分镜工作台</p><B onClick={()=>setShowP(true)}><Plus className="size-4"/>新建或打开项目</B><ProjModal open={showP} onClose={()=>setShowP(false)} list={list} aid={aid} setAid={setAid} onNew={newP} onDel={delP} onRen={renP} Icon={Film} sub={(p:SFProj)=>`${p.shots.length}镜`} npn={npn} setNpn={setNpn} renOpen={renO} setRenOpen={setRenO}/></div>;
 return <div className="max-w-7xl mx-auto px-4 py-6"><div className="flex justify-between mb-4 flex-wrap gap-2"><div><h1 className="text-lg font-serif font-bold">镜序 ShotFlow <Badge v="amber">主项目</Badge></h1><p className="text-[11px] text-muted-foreground">AI 短视频脚本与分镜工作台</p></div><div className="flex gap-1.5 flex-wrap"><B variant="outline" onClick={()=>setShowP(true)}>📁 {active.title}</B><B variant="outline" onClick={()=>setShowV(true)}><History className="size-3.5"/>版本</B><B variant="outline" onClick={()=>setShowC(true)}><Eye className="size-3.5"/>对比</B><B variant="outline" onClick={()=>expCSV(shots,active.title)}><Download className="size-3.5"/>CSV</B><B variant="outline" onClick={()=>expShoot(shots,active.title)}>拍摄清单</B></div></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card c="p-3 space-y-2"><label className="text-xs">主题</label><Input value={brief.topic} onChange={(e:ChangeEvent<HTMLInputElement>)=>updB('topic',e.target.value)}/><label className="text-xs">受众</label><Input value={brief.audience} onChange={(e:ChangeEvent<HTMLInputElement>)=>updB('audience',e.target.value)}/><label className="text-xs">目标时长（≥15秒正整数）</label><Input type="number" value={brief.duration} onChange={(e:ChangeEvent<HTMLInputElement>)=>updB('duration',e.target.value)}/><label className="text-xs">已有文字</label><TA value={brief.text} onChange={(v:string)=>updB('text',v)} rows={4}/><B c="w-full" onClick={genAll} disabled={loading==='all'}><Sparkles className="size-3.5"/>{loading==='all'?'生成中...':'生成分镜'}</B></Card><div className="lg:col-span-2 space-y-3"><Card c="p-3 flex justify-between flex-wrap gap-2"><div><Clock className="inline size-4 mr-1"/><b>{total}s</b> / {max}s · {shots.length}镜</div><div>{over?<Badge v="red">已超限 {total-max}s</Badge>:total>0&&<Badge v="green">时长合适</Badge>} <B variant="outline" onClick={addShot}><Plus className="size-3.5"/>添加</B></div></Card>{!shots.length?<Card c="p-8 text-center text-sm text-muted-foreground">暂无镜头</Card>:shots.map(s=><ShotCard key={s.id} s={s} onEdit={setEditId} onLock={toggleLock} onDel={delShot} onRegen={genOne} onDS={onDS} onDO={onDO} onDr={onDr} loading={loading}/>)}</div></div>
 {editId&&(()=>{const s=shots.find(x=>x.id===editId);if(!s)return null;return <Modal t={`编辑镜头 ${s.n}`} onClose={()=>setEditId(null)} w="max-w-lg"><div className="space-y-2"><Input type="number" value={s.dur} onChange={(e:ChangeEvent<HTMLInputElement>)=>updShot(s.id,'dur',e.target.value)}/>{[['景别','st'],['机位','cam'],['画面','desc'],['动作','act'],['旁白','vo'],['字幕','sub'],['音效','audio'],['转场','tr'],['AI提示词','prompt']].map(([l,k])=><div key={k}><label className="text-xs">{l}</label><Input value={(s as any)[k]} onChange={(e:ChangeEvent<HTMLInputElement>)=>updShot(s.id,k,e.target.value)}/></div>)}</div></Modal>})()}
 <ProjModal open={showP} onClose={()=>setShowP(false)} list={list} aid={aid} setAid={setAid} onNew={newP} onDel={delP} onRen={renP} Icon={Film} sub={(p:SFProj)=>`${p.shots.length}镜`} npn={npn} setNpn={setNpn} renOpen={renO} setRenOpen={setRenO}/>
 {showV&&<Modal t="版本管理" onClose={()=>setShowV(false)}><div className="flex gap-2"><Input value={vn} onChange={(e:ChangeEvent<HTMLInputElement>)=>setVn(e.target.value)} placeholder="版本名"/><B onClick={saveVer}><Save className="size-3.5"/>保存</B></div>{active.versions.map(v=><div key={v.id} className="p-2 mt-2 bg-muted rounded flex justify-between"><span>{v.name} · {v.shots.length}镜</span><B variant="outline" onClick={()=>save(v.shots)}>恢复</B></div>)}</Modal>}
 {showC&&<Modal t="版本对比" onClose={()=>setShowC(false)}><div className="grid grid-cols-2 gap-2">{[['版本A',cmpV1,setCmpV1],['版本B',cmpV2,setCmpV2]].map(([l,v,setV]:any)=><div key={l}><label className="text-xs">{l}</label><select value={v} onChange={(e:ChangeEvent<HTMLSelectElement>)=>setV(e.target.value)} className="w-full h-9 border rounded"><option value="">选择</option><option value="curr">当前状态</option>{active.versions.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>)}</div>{cmpV1&&cmpV2&&<div className="grid grid-cols-4 gap-2 mt-3">{[['新增',cmpRes.a,'green'],['删除',cmpRes.d,'red'],['修改',cmpRes.m,'amber'],['不变',cmpRes.u,'outline']].map(([l,n,v]:any)=><Badge key={l} v={v}>{l} {n}</Badge>)}</div>}</Modal>}
 </div>;
}
